### ISSUE TITLE
 Unknown account spending response

### ISSUE THREAD

**Issue by manonstreet** [pantherale0/pyfamilysafety#4]
Running the test harness produces the following error
`pyfamilysafety.account WARNING: Unknown account spending response, please report to developer. {'askAParentEnabled': False, 'balances': []}`

This same error also reported in the ha integration.

**Comment by pantherale0** [comment]
Balances seem odd, might be because something isn't enabled on your account for it to work.

Nothing breaking though just prevents the below (at least in HA) from working:

![SmartSelect_20240227_184046_Home Assistant](https://github.com/pantherale0/pyfamilysafety/assets/7346615/aa129f7c-6fcc-43d2-9e04-092d475f95be)

**Comment by manonstreet** [comment]
I do have spending controls disabled for my kids, so that may be the issue.  This does get rather noisy in HA though.  Perhaps you can suppress this message for such cases?

```Logger: pyfamilysafety.account
Source: custom_components/family_safety/coordinator.py:42
Integration: Microsoft Family Safety ([documentation](https://github.com/pantherale0/ha-familysafety), [issues](https://github.com/pantherale0/ha-familysafety/issues))
First occurred: February 27, 2024 at 7:47:27 PM (1578 occurrences)
Last logged: 10:14:26 AM

Unknown account spending response, please report to developer. {'askAParentEnabled': False, 'balances': []}
Unknown account spending response, please report to developer. {'askAParentEnabled': True, 'balances': []}```

**Comment by manonstreet** [comment]
I went ahead an enabled family spending monitoring, but I am still receiving the error.  I wonder if it's because I have never funded the account?  It looks like balances is returning a null value (as opposed to $0), and the module does not account for this?

**Comment by manonstreet** [comment]
I've modified the package on my end and commented out line 85 of account.py so the function is now:

```
    async def _get_account_balance(self):
        """Updates the account balance."""
        response = await self._api.send_request(
            endpoint="get_user_spending",
            USER_ID=self.user_id
        )
        response = response["json"]
        balances = response.get("balances", [])
        if len(balances) == 1:
            self.account_balance = balances[0]["balance"]
            self.account_currency = balances[0]["currency"]
            return
        #_LOGGER.warning("Unknown account spending response, please report to developer. %s", response)
        return
```

This solves my issue.

My understanding is that for those of us that have never deposited any funds, the balances array is null and therefore will never have a length of 1.  Catching this error generates many unnecessary warnings, especially when using the homeassistant integration.  If you agree, can you kindly remove the warning from your upstream package?

Thanks!

**Comment by pantherale0** [comment]
Log spam removed in 1.0.0
